
<LoginTextInput@TextInput>:
    font_size: int(self.height/2)

<CustomLabel@Label>:
    font_size: 18
    halign: 'left'
    #font_name: 'font/stocky'
    color: [0, 0, 0, 1]
    #size_hint: 0.15, .5

<RootLayout@BoxLayout>:
    orientation: 'vertical'
    padding: [10, 50, 10, 50]
    spacing: 20

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            # self here refers to the widget i.e BoxLayout
            pos: self.pos
            size: self.size